version = 1

[merge]
automerge_label = "ğŸš€!"
block_on_neutral_required_check_runs = true
method = "squash"

[merge.message]
title = "pull_request_title"
body = "pull_request_body"
strip_html_comments = true

[update]
autoupdate_label = "â™»ï¸!"
