version: '3.2'

services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: 'verdaccio'
    networks:
      - 'node-network'
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - 4873:4873
    volumes:
      - type: bind
        source: ./dev/build/verdaccio/
        target: /bud/dev/build/verdaccio

  bud:
    build: ./dev/build/node
    container_name: 'bud'
    networks:
      - 'node-network'
    user: 'node'
    working_dir: /bud
    volumes:
      - type: bind
        source: ./
        target: /bud
    command: bash -c /bud/dev/build/node/init.sh

volumes:
  verdaccio:
  bud:

networks:
  node-network:
    driver: bridge
