[build]
  base = "./"
  publish = "sources/@repo/docs/build/"
  command = "yarn docusaurus build"

[[redirects]]
  from = "http://budjs.netlify.app/*"
  to = "https://bud.js.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://budjs.netlify.app/*"
  to = "https://bud.js.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://bud.js.org/docs/bud.template"
  to = "https://bud.js.org/docs/bud.html"
  status = 301
  force = true

[[redirects]]
  from = "https://bud.js.org/packages/wordpress-hmr"
  to = "https://bud.js.org/extensions/bud-preset-wordpress"
  status = 301
  force = true

[[redirects]]
  from = "https://bud.js.org/guides/*"
  to = "https://bud.js.org/learn/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://bud.js.org/docs/*"
  to = "https://bud.js.org/reference/:splat"
  status = 301
  force = true
