name: Build & Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
        node:
          - 16.x

    name: test node@${{matrix.node}}/${{matrix.platform}}
    runs-on: ${{matrix.platform}}

    steps:
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Restore
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: yarn install
        run: |
          yarn install

      - name: yarn @bud build
        run: |
          yarn @bud build

      - name: yarn @bud lint dependencies
        run: |
          yarn @bud lint dependencies

      - name: yarn @bud lint
        run: |
          yarn @bud lint

      - name: yarn @bud format
        run: |
          yarn @bud format --no-fix

      - name: yarn @bud lint exports
        run: |
          yarn @bud lint exports

      - name: yarn @bud test unit
        run: |
          yarn @bud test unit

      - name: yarn @bud registry install
        run: |
          yarn @bud registry install

      - name: yarn @bud registry start
        run: |
          yarn @bud registry start

      - name: yarn @bud release --tag latest
        run: |
          yarn @bud release --tag latest

      - name: yarn @bud test integration
        run: |
          yarn @bud test integration

      - name: yarn @bud test e2e
        run: |
          yarn @bud test e2e
