name: test

on:
  push:
    branches:
      - next
    tags:
      - '!*' # Do not execute on tags
    paths:
      - packages/*/src/*
      - packages/*/src/**/*
      - test/*
      - '*.json'
      - yarn.lock
  pull_request:
    paths:
      - '!*.MD'
      - '!*.md'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macOS-latest, windows-latest]
        node: ['12']
    name: test ${{matrix.node}}/${{matrix.platform}}
    runs-on: ${{matrix.platform}}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: ${{matrix.node}}
    - run: npm install -g yarn
    - run: yarn global add lerna
    - run: yarn install
    - run: yarn build
    - run: yarn test:coverage
